version: "3.7"

services:
  wgtcrm-web:
    image: nginx:1.10.3
    container_name: wgtcrm-web
    ports:
      - "10080:80"
      - "10430:443"
    restart: always
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d:ro"
      - ".:/var/www/wgtcrm"
    depends_on:
      - "wgtcrm-php"
      - "wgtcrm-mysql"
    networks:
      - wgtcrm

  wgtcrm-php:
    image: devmagellan/wgt-php:latest
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: wgtcrm-php
    environment:
      APP_ENV: local
    restart: always
    working_dir: /var/www/wgtcrm
    volumes:
      - "./docker/php:/usr/local/etc/php:ro"
      #- ".:/var/www/wgtcrm"
    networks:
      - wgtcrm
    secrets:
      - source: ssh_key
        target: /home/docker/.ssh/id_rsa

  wgtcrm-mysql:
    image: mysql:5.7.30
    container_name: wgtcrm-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'wgtdev'
      MYSQL_USER: 'wgtdev'
      MYSQL_PASSWORD: 'wgtdev'
      MYSQL_ROOT_PASSWORD: 'wgtdev'
    ports:
      - '13306:3306'
    expose:
      - '3306'
    volumes:
      - "./docker/tmp/mysql:/var/lib/mysql"
    networks:
      - wgtcrm

  wgtcrm-graphql-browser:
    build: ./docker/graphql-browser
    container_name: wgtcrm-graphql-browser
    restart: always
    command: npm run start
    ports:
      - '4300:3000'
    networks:
      - wgtcrm

networks:
  wgtcrm:
    name: wgtcrm
    driver: bridge
secrets:
  ssh_key:
    file: ~/.ssh/id_rsa
